version: "3.7"

services:
    php:
        build: 
            context: './php/'
            args:
                PHP_VERSION: ${PHP_VERSION}
        volumes:
            - ${PROJECT_ROOT}/:/var/www/html/
        #networks:
        #    - backend
        container_name: php
    apache:
        build:
            context: './apache/'
            args:
                APACHE_VERSION: ${APACHE_VERSION}
        depends_on:
            - php
            - mysql
        ports:
            - "8080:80"
        volumes:
            - ${PROJECT_ROOT}/:/var/www/html/
        #networks:
        #    - frontend
        #    - backend
        container_name: apache
    mysql:
        image: mysql:${MYSQL_VERSION:-latest}
        restart: always
        ports:
            - "3307:3306"
        volumes:
            - ./data:/var/lib/mysql
        #networks:
        #    - backend
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        container_name: mysql
#networks:
#    frontend:
#    backend:
#volumes:
#    data: