version: "3.7"
services: 
    nginx:
        image: nginx:1.21-alpine
        container_name: nginx
        restart: always
        ports: 
            - 8080:80
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        restart: always
        environment: 
            MYSQL_DATABASE: larabel
            MYSQL_USER: mortega
            MYSQL_PASSWORD: abc123**
            MYSQL_ROOT_PASSWORD: abc123admin
        ports: 
            - 3307:3306
        volumes: 
            - ./mysql:/var/lib/mysql   
    php:
        build: 
            context: .
            dockerfile: Dockerfile 
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports: 
            - 9000:80
        
